### PR TITLE
Fixed the set-up scripts and added an TanDEM 90m downloader

### PR DESCRIPTION
**Pull request by Developer66**
I recoded the open-elevation project a bit to make it working again and I added a java downloader for TanDEM 90m data

Also added a link to 30m Europe data

### CODE REVIEW

**Comment by ianaz** [comment]
Nice, weird that noone reviewed this. I'm going to try it out

**Comment by Developer66** [comment]
Hey,
it's very weird that @Jorl17 did not accept this review. The Project seems to be offline but @Jorl17 said its not. See #29 but since this comment nothing happen. Hope there will be some movement in this repository in the future.

**Comment by sytolk** [comment]
@Developer66 maybe its better to continue work in your fork ? I'll will push PR here

**Comment by Jorl17** [comment]
Project's still waiting on the development team, which got delayed, unfortunately.

I will probably review this PR (and very likely merge it) during this week. Thank you for your work :)

**Comment by sytolk** [comment]
feels free to import it here: https://github.com/Developer66/open-elevation/pull/8

**Comment by Jorl17** [comment]
I have taken a superficial look at the PR. I will probably be making some very slight adjustments to the Java code and adding you as a credited contributor in the README later this week. Thank you for your work!

**Review by RatmirAgliullin — APPROVED** [review]

**Comment by Developer66** [comment]
due to the inactivity of this repo and the long on hold status, i am now closing the pullrequest. Unfortunately, it does not look like it will ever be accepted.

**Pull request closed without merging**
