### PR TITLE
Update source of worldwide SRTM 250m dataset

### LINKED ISSUE #42: Unable to download the whole world dataset 404
`docker run -t -i -v $(pwd)/data:/code/data openelevation/open-elevation /code/create-dataset.sh`
```

--2021-03-28 17:04:33--  http://gisweb.ciat.cgiar.org/TRMM/SRTM_Resampled_250m/SRTM_NE_250m_TIF.rar
Resolving gisweb.ciat.cgiar.org (gisweb.ciat.cgiar.org)... 45.5.184.33
Connecting to gisweb.ciat.cgiar.org (gisweb.ciat.cgiar.org)|45.5.184.33|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-03-28 17:04:34 ERROR 404: Not Found.
```

### PR DESCRIPTION
**Pull request by zstadler**
Resolve #42

### CODE REVIEW

**Comment by zstadler** [comment]
@Jorl17,
Could you have a look at this?

**Comment by Jorl17** [comment]
Hi, @zstadler .

It's not been lost or forgotten! In the next couple of hours I'm planning to push a serious of well-needed updates, both to github and dockerhub. I believe your PR is in one of these updates.

In case you use the free API at https://www.open-elevation.com you might also have noticed that for the first time in about 2 years it is handling the load pretty well. I wonder how many services broke because the API is suddenly faster and more reliable?

**Comment by zstadler** [comment]
Thank you @Jorl17 for merging this PR.

I'm looking forward towards the performance improvements!

My hope is to use the repository for creating a local high resolution elevation service. Everything worked great in my development environment, but I've seen some unexplained reliability issues when the setup was deployed to a busy and weaker production environment.

**Comment by Jorl17** [comment]
Ah, sadly, the performance improvements, at this time, are only in the public server (they were mostly unrelated to code and focused on hardware/hosting) :( 

If your company so desires, you can contact me and I can arrange for some consulting job with debugging, troubleshooting and improving the performance of your services. Anyway, best of luck!

**Comment by zstadler** [comment]
Thanks for the offer!
This is for [IsraelHiking.osm.org.il](https://israelhiking.osm.org.il). We're developing it in our free time.

**Pull request merged**
